name: GitHub Commit Statistics

on:
  schedule:
    - cron: '0 23 * * *'  #  run at 00:00 every day
  workflow_dispatch:      #  allow manual trigger



jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv
    
    - name: Run statistics script
      env:
        GITHUB_USERNAME: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python commit_count.py
    
    - name: Create new branch and commit changes
      run: |
        # 获取当前日期作为分支名
        branch_name="stats/$(date +'%Y-%m-%d')"
        
        # 配置 Git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 创建新分支
        git checkout -b $branch_name
        
        # 添加更改并提交
        git add github_commit_count.md
        git commit -m "Update GitHub commit statistics for $(date +'%Y-%m-%d')"
        
        # 推送新分支
        git push origin $branch_name
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: "Update GitHub commit statistics $(date +'%Y-%m-%d')"
        body: "Automated statistics update for $(date +'%Y-%m-%d')"
        branch: "stats/$(date +'%Y-%m-%d')"
        base: ${{ github.ref }}
        delete-branch: true