name: GitHub Commit Statistics

on:
  schedule:
    - cron: '0 23 * * *'  # UTC 23:00 (UTC+1 00:00)
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:  # 添加明确的权限
      contents: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 获取完整的git历史
        token: ${{ secrets.GITHUB_TOKEN }}  # 明确指定token
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv
    
    - name: Set date
      run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    
    - name: Run statistics script
      env:
        GITHUB_USERNAME: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python commit_count.py
    
    - name: Create new branch and commit changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        branch_name="stats/${{ env.DATE }}"
        
        # Delete existing local branch (if exists)
        git branch -D $branch_name || true
        
        # Delete existing remote branch (if exists)
        git push origin --delete $branch_name || true
        
        # Create and push new branch
        git checkout -b $branch_name
        git add github_commit_count.md
        git commit -m "Update GitHub commit statistics for ${{ env.DATE }}"
        git push -f --set-upstream origin $branch_name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Update GitHub commit statistics ${{ env.DATE }}"
        body: "Automated statistics update for ${{ env.DATE }}"
        branch: "stats/${{ env.DATE }}"
        base: ${{ github.ref }}
        delete-branch: true