name: GitHub Commit Statistics

on:
  schedule:
    - cron: '0 23 * * *'  #  run at 00:00 every day
  workflow_dispatch:      #  allow manual trigger



jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run statistics script
      env:
        GITHUB_USERNAME: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python commit_stats.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add github_stats.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update GitHub commit statistics" && git push)